export const AGENT_UPDATE = 'agent:config:update'
export const SCRIPT_TYPE = 'ScriptJob'
export const SCRAPER_TYPE = 'ScraperJob'
export const APPROVAL_TYPE = 'ApprovalJob'
export const DUMMY_TYPE = 'DummyJob'
export const NOTIFICATION_TYPE = 'NotificationJob'
export const WORKFLOW_TYPE = 'WorkflowJob'
export const DEFAULT_TYPE = 'Job'
export const AGENT_UPDATE_TYPE = 'AgentUpdateJob'

export const ORIGIN_USER = 'user'
export const ORIGIN_WORKFLOW = 'workflow'
export const ORIGIN_TRIGGER_BY = 'trigger_by'
export const ORIGIN_SCHEDULER = 'scheduler'
