module.exports.acl = {
  root: {
    "events"                : ['*'],
    "hoststats"             : ['*'],
    "palanca"               : ['*'],
    "tasks"                 : ['*'],
    "script"                : ['*'],
    "resource"              : ['*'],
    "hostgroup"             : ['*'],
    "hostgrouptasktemplate" : ['*'],
    "hostgroupmonitortemplate" : ['*'],
    "auth"                  : ['*'],
    "user"                  : ['*'],
    // only root
    "process"               : ['*'],
    "customer"              : ['*'],
  },
  owner: {
    "events"                : ['*'],
    "hoststats"             : ['*'],
    "palanca"               : ['*'],
    "tasks"                 : ['*'],
    "script"                : ['*'],
    "resource"              : ['*'],
    "hostgroup"             : ['*'],
    "hostgrouptasktemplate" : ['*'],
    "hostgroupmonitortemplate" : ['*'],
    "auth"                  : ['*'],
    "user"                  : ['profile','setcustomer'],
  },
  admin: {
    "events"                : ['*'],
    "hoststats"             : ['*'],
    "palanca"               : ['*'],
    "tasks"                 : ['*'],
    "script"                : ['*'],
    "resource"              : ['*'],
    "hostgroup"             : ['*'],
    "hostgrouptasktemplate" : ['*'],
    "hostgroupmonitortemplate" : ['*'],
    "auth"                  : ['login', 'activate', 'google', 'connect', 'unlink', 'logout'],
    "user"                  : ['profile','setcustomer'],
  },
  user: {
    "events"    : ['*'],
    "hoststats" : ['*'],
    "palanca"   : ['*'],
    "auth"      : ['login', 'activate', 'google', 'connect', 'unlink', 'logout'],
    "user"      : ['profile','setcustomer'],
  }
};
