module.exports = {
  'lifecycle:ready': 'Queued',
  'lifecycle:assigned': 'Task is being executed',
  'lifecycle:finished': 'Finished running',
  'lifecycle:canceled': 'Has been canceled',
  'lifecycle:terminated': 'Terminated abnormally',
  'lifecycle:completed': 'Completed',
  'lifecycle:onhold': 'On hold',
  updates_stopped: 'Has gone silent',
  updates_started: 'Came back to life',
  failure: 'Requires your attention',
  recovered: 'Came back to normal',
  'file:restored': 'File restored',
  'host:stats:normal': 'Host stats back to normal',
  'host:stats:cpu:high': 'Host CPU high',
  'host:stats:mem:high': 'Host memory high',
  'host:stats:disk:high': 'Host disk high',
  'host:stats:cache:high': 'Host cache high',
  'webhook': 'Triggered'
}
