name: Docker Image CI

on:
  push:
    branches: [ "development" ]
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: get git describe tag
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: theeyeteam/theeye-web
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          #- name: Set APP_VERSION env
          #  run: echo "APP_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          #  run: echo "APP_VERSION=$(git describe)" >> $GITHUB_ENV
      - name: Env
        run: |
          echo App Version
          echo $APP_VERSION
          echo ${{ steps.tagName.outputs.tag }}
      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV=production
            APP_VERSION=${{ steps.tagName.outputs.tag }}
